const imagePath = '../src/img/';
const audioPath = '../src/audio/';
const cards = [
  [
    {
      word: 'cry',
      translation: 'плакать',
      imageUrl: `${imagePath}cry.jpg`,
      audioUrl: `${audioPath}cry.mp3`,
    },
    {
      word: 'dance',
      translation: 'танцевать',
      imageUrl: `${imagePath}dance.jpg`,
      audioUrl: `${audioPath}dance.mp3`,
    },
    {
      word: 'dive',
      translation: 'нырять',
      imageUrl: `${imagePath}dive.jpg`,
      audioUrl: `${audioPath}dive.mp3`,
    },
    {
      word: 'draw',
      translation: 'рисовать',
      imageUrl: `${imagePath}draw.jpg`,
      audioUrl: `${audioPath}draw.mp3`,
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      imageUrl: `${imagePath}fish.jpg`,
      audioUrl: `${audioPath}fish.mp3`,
    },
    {
      word: 'fly',
      translation: 'летать',
      imageUrl: `${imagePath}fly.jpg`,
      audioUrl: `${audioPath}fly.mp3`,
    },
    {
      word: 'hug',
      translation: 'обнимать',
      imageUrl: `${imagePath}hug.jpg`,
      audioUrl: `${audioPath}hug.mp3`,
    },
    {
      word: 'jump',
      translation: 'прыгать',
      imageUrl: `${imagePath}jump.jpg`,
      audioUrl: `${audioPath}jump.mp3`,
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      imageUrl: `${imagePath}open.jpg`,
      audioUrl: `${audioPath}open.mp3`,
    },
    {
      word: 'play',
      translation: 'играть',
      imageUrl: `${imagePath}play.jpg`,
      audioUrl: `${audioPath}play.mp3`,
    },
    {
      word: 'point',
      translation: 'указывать',
      imageUrl: `${imagePath}point.jpg`,
      audioUrl: `${audioPath}point.mp3`,
    },
    {
      word: 'ride',
      translation: 'ездить',
      imageUrl: `${imagePath}ride.jpg`,
      audioUrl: `${audioPath}ride.mp3`,
    },
    {
      word: 'run',
      translation: 'бегать',
      imageUrl: `${imagePath}run.jpg`,
      audioUrl: `${audioPath}run.mp3`,
    },
    {
      word: 'sing',
      translation: 'петь',
      imageUrl: `${imagePath}sing.jpg`,
      audioUrl: `${audioPath}sing.mp3`,
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      imageUrl: `${imagePath}skip.jpg`,
      audioUrl: `${audioPath}skip.mp3`,
    },
    {
      word: 'swim',
      translation: 'плавать',
      imageUrl: `${imagePath}swim.jpg`,
      audioUrl: `${audioPath}swim.mp3`,
    },
  ],
  [
    {
      word: 'argue',
      translation: 'спорить',
      imageUrl: `${imagePath}argue.jpg`,
      audioUrl: `${audioPath}argue.mp3`,
    },
    {
      word: 'build',
      translation: 'строить',
      imageUrl: `${imagePath}build.jpg`,
      audioUrl: `${audioPath}build.mp3`,
    },
    {
      word: 'carry',
      translation: 'нести',
      imageUrl: `${imagePath}carry.jpg`,
      audioUrl: `${audioPath}carry.mp3`,
    },
    {
      word: 'catch',
      translation: 'ловить',
      imageUrl: `${imagePath}catch.jpg`,
      audioUrl: `${audioPath}catch.mp3`,
    },
    {
      word: 'drive',
      translation: 'водить машину',
      imageUrl: `${imagePath}drive.jpg`,
      audioUrl: `${audioPath}drive.mp3`,
    },
    {
      word: 'drop',
      translation: 'падать',
      imageUrl: `${imagePath}drop.jpg`,
      audioUrl: `${audioPath}drop.mp3`,
    },
    {
      word: 'pull',
      translation: 'тянуть',
      imageUrl: `${imagePath}pull.jpg`,
      audioUrl: `${audioPath}pull.mp3`,
    },
    {
      word: 'push',
      translation: 'толкать',
      imageUrl: `${imagePath}push.jpg`,
      audioUrl: `${audioPath}push.mp3`,
    },
  ],
  [
    {
      word: 'big',
      translation: 'большой',
      imageUrl: `${imagePath}big.jpg`,
      audioUrl: `${audioPath}big.mp3`,
    },
    {
      word: 'small',
      translation: 'маленький',
      imageUrl: `${imagePath}small.jpg`,
      audioUrl: `${audioPath}small.mp3`,
    },
    {
      word: 'fast',
      translation: 'быстрый',
      imageUrl: `${imagePath}fast.jpg`,
      audioUrl: `${audioPath}fast.mp3`,
    },
    {
      word: 'slow',
      translation: 'медленный',
      imageUrl: `${imagePath}slow.jpg`,
      audioUrl: `${audioPath}slow.mp3`,
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      imageUrl: `${imagePath}friendly.jpg`,
      audioUrl: `${audioPath}friendly.mp3`,
    },
    {
      word: 'unfriendly',
      translation: 'недружелюбный',
      imageUrl: `${imagePath}unfriendly.jpg`,
      audioUrl: `${audioPath}unfriendly.mp3`,
    },
    {
      word: 'young',
      translation: 'молодой',
      imageUrl: `${imagePath}young.jpg`,
      audioUrl: `${audioPath}young.mp3`,
    },
    {
      word: 'old',
      translation: 'старый',
      imageUrl: `${imagePath}old.jpg`,
      audioUrl: `${audioPath}old.mp3`,
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      imageUrl: `${imagePath}cat.jpg`,
      audioUrl: `${audioPath}cat.mp3`,
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      imageUrl: `${imagePath}chick.jpg`,
      audioUrl: `${audioPath}chick.mp3`,
    },
    {
      word: 'chicken',
      translation: 'курица',
      imageUrl: `${imagePath}chicken.jpg`,
      audioUrl: `${audioPath}chicken.mp3`,
    },
    {
      word: 'dog',
      translation: 'собака',
      imageUrl: `${imagePath}dog.jpg`,
      audioUrl: `${audioPath}dog.mp3`,
    },
    {
      word: 'horse',
      translation: 'лошадь',
      imageUrl: `${imagePath}horse.jpg`,
      audioUrl: `${audioPath}horse.mp3`,
    },
    {
      word: 'pig',
      translation: 'свинья',
      imageUrl: `${imagePath}pig.jpg`,
      audioUrl: `${audioPath}pig.mp3`,
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      imageUrl: `${imagePath}rabbit.jpg`,
      audioUrl: `${audioPath}rabbit.mp3`,
    },
    {
      word: 'sheep',
      translation: 'овца',
      imageUrl: `${imagePath}sheep.jpg`,
      audioUrl: `${audioPath}sheep.mp3`,
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      imageUrl: `${imagePath}bird.jpg`,
      audioUrl: `${audioPath}bird.mp3`,
    },
    {
      word: 'fish',
      translation: 'рыба',
      imageUrl: `${imagePath}fish1.jpg`,
      audioUrl: `${audioPath}fish.mp3`,
    },
    {
      word: 'frog',
      translation: 'жаба',
      imageUrl: `${imagePath}frog.jpg`,
      audioUrl: `${audioPath}frog.mp3`,
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      imageUrl: `${imagePath}giraffe.jpg`,
      audioUrl: `${audioPath}giraffe.mp3`,
    },
    {
      word: 'lion',
      translation: 'лев',
      imageUrl: `${imagePath}lion.jpg`,
      audioUrl: `${audioPath}lion.mp3`,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      imageUrl: `${imagePath}mouse.jpg`,
      audioUrl: `${audioPath}mouse.mp3`,
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      imageUrl: `${imagePath}turtle.jpg`,
      audioUrl: `${audioPath}turtle.mp3`,
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      imageUrl: `${imagePath}dolphin.jpg`,
      audioUrl: `${audioPath}dolphin.mp3`,
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      imageUrl: `${imagePath}skirt.jpg`,
      audioUrl: `${audioPath}skirt.mp3`,
    },
    {
      word: 'pants',
      translation: 'брюки',
      imageUrl: `${imagePath}pants.jpg`,
      audioUrl: `${audioPath}pants.mp3`,
    },
    {
      word: 'blouse',
      translation: 'блузка',
      imageUrl: `${imagePath}blouse.jpg`,
      audioUrl: `${audioPath}blouse.mp3`,
    },
    {
      word: 'dress',
      translation: 'платье',
      imageUrl: `${imagePath}dress.jpg`,
      audioUrl: `${audioPath}dress.mp3`,
    },
    {
      word: 'boot',
      translation: 'ботинок',
      imageUrl: `${imagePath}boot.jpg`,
      audioUrl: `${audioPath}boot.mp3`,
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      imageUrl: `${imagePath}shirt.jpg`,
      audioUrl: `${audioPath}shirt.mp3`,
    },
    {
      word: 'coat',
      translation: 'пальто',
      imageUrl: `${imagePath}coat.jpg`,
      audioUrl: `${audioPath}coat.mp3`,
    },
    {
      word: 'shoe',
      translation: 'туфли',
      imageUrl: `${imagePath}shoe.jpg`,
      audioUrl: `${audioPath}shoe.mp3`,
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      imageUrl: `${imagePath}sad.jpg`,
      audioUrl: `${audioPath}sad.mp3`,
    },
    {
      word: 'angry',
      translation: 'сердитый',
      imageUrl: `${imagePath}angry.jpg`,
      audioUrl: `${audioPath}angry.mp3`,
    },
    {
      word: 'happy',
      translation: 'счастливый',
      imageUrl: `${imagePath}happy.jpg`,
      audioUrl: `${audioPath}happy.mp3`,
    },
    {
      word: 'tired',
      translation: 'уставший',
      imageUrl: `${imagePath}tired.jpg`,
      audioUrl: `${audioPath}tired.mp3`,
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      imageUrl: `${imagePath}surprised.jpg`,
      audioUrl: `${audioPath}surprised.mp3`,
    },
    {
      word: 'scared',
      translation: 'испуганный',
      imageUrl: `${imagePath}scared.jpg`,
      audioUrl: `${audioPath}scared.mp3`,
    },
    {
      word: 'smile',
      translation: 'улыбка',
      imageUrl: `${imagePath}smile.jpg`,
      audioUrl: `${audioPath}smile.mp3`,
    },
    {
      word: 'laugh',
      translation: 'смех',
      imageUrl: `${imagePath}laugh.jpg`,
      audioUrl: `${audioPath}laugh.mp3`,
    },
  ],
];

export default cards;
